version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: sl-web
        working_dir: /app
        networks:
            - app-net
        ports:
            - 80:80
        depends_on:
            - node

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        container_name: sl-node
        working_dir: /app
        volumes:
            - ./.env:/app/secret/.env
            - ./service-account-file.json:/app/secret/service-account-file.json
        ports:
            - 8000:8000
        networks:
            - app-net
        healthcheck:
            test: ["CMD-SHELL", "node /app/healthcheck.js"]
            interval: 10s
            timeout: 2s

networks:
    app-net:
        driver: bridge